name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'H2CO3_main'
  pull_request:
    branches:
      - 'H2CO3_main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'dragonwell'
          cache: gradle

      - name: Build Debug .apk
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: H2CO3-debug
          path: H2CO3/build/outputs/apk/debug/*.apk